### ISSUE TITLE
Guake not working

### ISSUE THREAD

**Issue by TobyThomasTech** [void-linux/void-packages#11743]
Hi, 
I get the following error when I try to start Guake.  

Guake not running, starting it

(guake:26620): dbind-WARNING **: 22:36:38.157: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 319, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 448, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 333, in main
    from guake.guake_app import Guake
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 54, in <module>
    from guake.about import AboutDialog
  File "/usr/lib/python3.6/site-packages/guake/about.py", line 28, in <module>
    from guake.common import gladefile
  File "/usr/lib/python3.6/site-packages/guake/common.py", line 30, in <module>
    from guake.paths import GLADE_DIR
  File "/usr/lib/python3.6/site-packages/guake/paths.py", line 21, in <module>
    from pkg_resources import Requirement
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by yopito** [comment]
please fill and use the template's issue: it helps about describing your context (voidlinux's status, package version, etc).

**Comment by TobyThomasTech** [comment]
@yopito My apologies and thanks for your quick response. I will post it with the issue template later today.

**Comment by Johnnynator** [comment]
@TobyThomasTech I pushed an update for the package, it should have this issue resolved.

**Comment by TobyThomasTech** [comment]
@Johnnynator Thanks for your response. Unfortunate the issue still persist. 
I have added the output of *xuname* as requested by @yopito.

**xuname:** Void 4.19.44_1 x86_64 GenuineIntel notuptodate rrFFF

**Error msg when running command guake:**

(guake:2927): dbind-WARNING **: 09:45:51.434: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 359, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 373, in main
    from guake.guake_app import Guake
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 56, in <module>
    from guake.about import AboutDialog
  File "/usr/lib/python3.6/site-packages/guake/about.py", line 28, in <module>
    from guake.common import gladefile
  File "/usr/lib/python3.6/site-packages/guake/common.py", line 30, in <module>
    from guake.paths import GLADE_DIR
  File "/usr/lib/python3.6/site-packages/guake/paths.py", line 26, in <module>
    from pkg_resources import Requirement
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by Hoshpak** [comment]
@TobyThomasTech Guake needs setuptools which probably is already installed on most systems because some other package depends on it so no one else noticed before. I pushed an update to the package adding the missing dependency. Please update the package and try again.

**Comment by TobyThomasTech** [comment]
@Hoshpak Thanks a lot. I checked it now and it is working fine.
