### ISSUE TITLE
albert: calculator functionality will not load: undefined symbol in /usr/lib/albert/plugins/libcalculator.so

### ISSUE THREAD

**Issue by fusion809** [void-linux/void-packages#1438]
### System

* xuname: 
`Void 4.17.9_1 x86_64 GenuineIntel uptodate rrFF`
* package:  
  albert-0.14.21_2

### Expected behaviour
I was expecting Albert to allow for calculations in it (e.g. I could try out this example in it &mdash; https://camo.githubusercontent.com/0d47fbc5b2eaabb4444db79a5508ed8439100f4d/68747470733a2f2f692e696d6775722e636f6d2f42614d6c5769742e6a7067) when the option was enabled in its settings window, i.e. this:

![screenshot_void_20180804_020832](https://user-images.githubusercontent.com/4717341/43653426-5b82b1e0-978b-11e8-9e79-b0471d313b4e.png)

window. 

### Actual behaviour
This option could not be enabled and gave the error:

```bash
albert: symbol lookup error: /usr/lib/albert/plugins/libcalculator.so: undefined symbol: _ZN2mu10ParserBase7SetExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

when I tried to enable it. A variation on this error can also be seen in the screenshot above. 

### Steps to reproduce the behavior
1. Install Albert
2. Launch Albert, e.g. from a terminal (which would also allow you to see the above error in the terminal as well).
3. In the settings Albert will direct you to adjust, go to the "Extensions" tab and tick the box next to "Calculator" this error should then appear.

**Comment by pullmoll** [comment]
Should be solved by rebuilding albert with the gcc libstdc++ that dropped gcc4 compatibility.
If the update does not work, please open this issue again.

**Comment by fusion809** [comment]
I tried manually compiling it locally, uninstalling the packaged version, then installing my local version and it didn't fix it so I wouldn't imagine it would.

**Comment by pullmoll** [comment]
Ok, then it's got to be one of the dependencies which needs a rebuild, probably muparser or libqualculate - or both.

**Comment by pullmoll** [comment]
After updating `muparser` albert works as expected here.

**Comment by fusion809** [comment]
Same here. Took me a little while to check it out as for some reason xbps-src tries to download xorgproto-2018.4_1 instead of _2 for me and this error has been occurring for probably the past six hours now (https://forum.voidlinux.org/t/failed-to-download-xorgproto-2018-4-1-device-or-resource-busy/6392).

**Comment by Hoshpak** [comment]
This issue is documented in #1402 . Building the packages so you have them in you local repository usually helps around that. At least two packages will also need a rebuild for the muparser rebuild. I am currently testing and will open a PR shortly.
