### ISSUE TITLE
python3-3.8.1_1: broken, unresolvable shlib `libffi.so.6'

### ISSUE THREAD

**Issue by mnabid** [void-linux/void-packages#20336]
I was trying to compile nautilus and got the error: 

```
=> ERROR: glib-2.62.5_2: failed to install 'gettext-0.20.1_2' dependency! (error 8)
python3-3.8.1_1: broken, unresolvable shlib `libffi.so.6'
Transaction aborted due to unresolved shlibs.
```
**EDIT:**
libffi update to 3.3 is probably causing this error.

**Comment by pullmoll** [comment]
@mnabid Exactly. You'll have to wait until the packages are built:
https://build.voidlinux.org/waterfall
It may take some time because libffi affects a lot of big packages.

**Comment by mnabid** [comment]
Guess I'll wait then.

**Comment by q66** [comment]
@pullmoll btw, in order to unstage the musl repo, we'll need a new tarball for `ghc-bin`; do you think you could build one? In order to not repeat this problem, make sure *not* to build it with `--with-system-libffi`, as that's what's causing the whole mess for `x86_64-musl` only; my `ppc64le` tarball does not have the problem, nor do the official bindists.

**Comment by pullmoll** [comment]
@q66 Sure, I can do that. Is there a description how I build the x86_64-musl ghc-bin tarball?
I read I should "make binary-dist" but where?

**Comment by pullmoll** [comment]
FWIW Here's what I think could work:
+ In a x86_64-musl build env extract `bsdtar xvf /host/binpkgs/ghc-bin-8.6.5_1.x86_64.xbps`
+ Create a symlink for a fake `libffi.so.6` with `ln -sf libffi.so.7.1.0 /usr/lib/libffi.so.6`
+ Modify ghc template to **not** depend on `ghc-bin` for the host
+ Also remove the `configure_args="--with-system-libffi"` from the template
+ Add a `make_build_args="binary-dist"` (?)
+ `./xbps-src -m x86_64-musl pkg ghc`
+ Save the resulting tarball (?) somewhere

**Comment by q66** [comment]
i don't think the glibc build of `ghc` will work in a musl env... you need to take the existing musl `ghc-bin` tarball, extract it in your env, get a `libffi.so.6`, provide it, then build `ghc` with `binary-dist` like you said (having removed `--with-system-libffi`)

as for uploads: normally on `alpha.de.repo.voidlinux.org` in `distfiles` as usual

**Comment by q66** [comment]
i will take care of revbumping `stack` and the other haskell things that need rebuilding, as e.g. `stack` needs build fixes (like always...) and so on, i just need you to provide the bindist, since i can't build that myself (no spare x86_64 machine with enough power)

**Comment by pullmoll** [comment]
Oops, I of course extracted the ghc-bin-8.6.5_1.x86_64-musl.xbps and it seems to work so far. Currently running `make all` and will then try what `make binary-dist` gives me.

**Comment by q66** [comment]
alright. Make sure to try building `ghc` with it before we put it somewhere.

**Comment by pullmoll** [comment]
Yep. I'll upload it to my `https://distfiles.voidlinux.de` and see if it works.

**Comment by pullmoll** [comment]
The first try failed. The [tarball](https://distfiles.voidlinux.de/ghc-8.6.5-x86_64-void-linux-musl.tar.xz) is missing lots of files. I'll try again without manually going to the chroot, but rather preparing everything, e.g. need `tar` and `xz` in the host, to finally `make binary-dist` in `post_install()` and copy the result.

**Comment by pullmoll** [comment]
Ok, second try resulted in a much larger tarball with all files it seems:
[https://distfiles.voidlinux.de/ghc-8.6.5-x86_64-void-linux-musl.tar.xz](https://distfiles.voidlinux.de/ghc-8.6.5-x86_64-void-linux-musl.tar.xz)
Checksum e335578cf199588dbfd5a3c678a4fc0b0d44ec83771a902a01e510b993b3e01e
Building `ghc-bin-8.6.5_2` for `x86_64-musl` worked for me.

I wonder if we should add a `build_option="bindist"` to the `ghc` template to make it easier in the future.

Who's going to update `ghc-bin` or should we wait for someone to put in on `alpha.de.repo.voidlinux.org/distfiles` ?

**Comment by Duncaen** [comment]
Replaced the previous archive on https://alpha.de.repo.voidlinux.org/distfiles/ with the new one.

**Comment by q66** [comment]
the new tarball is now mirrored, i'll take care of properly bumping all the haskell things...

**Comment by Francesco149** [comment]
the libffi issues appear to be mostly resolved as a lot of rev bumped packages came through today

**Comment by q66** [comment]
yeah this is fixed (besides aarch64 builder, which has something wrong with it)

**Comment by mnabid** [comment]
Still getting same error for `i686` .

...and another error in `aarch64` and `aarch64-musl`: 
`=> ERROR: libffi-3.3_2: failed to fetch libffi-3.3.tar.gz.` I don't know why.

**Comment by Duncaen** [comment]
i686 should be unstaged now, aarch64 is still catching up.
https://build.voidlinux.org/waterfall
