### ISSUE TITLE
Gnome shows no users

### ISSUE THREAD

**Issue by axaxs** [void-linux/void-packages#3556]
### System

* xuname:  
  Void 4.18.12_2 x86_64-musl 
* package:  
  gnome, accountsservice

Apologies, I do not have void installed at the moment but was using the latest version in my testing two days ago. The above is a rough guess.

When logged in to gnome, the name is missing from the system menu that would allow for logout.  This does not affect actual behavior of submenus.

Further, when trying to view/edit users via the settings menu, it claims no users are found.

**Comment by loreb** [comment]
Can reproduce on a musl vm, not in glibc.

Btw, even if it'e unrelated: enabling dbus (as a gdm dependency) it outputs

`dbus[$pid]: Unknown username "rtkit" in message bus configuration file`

(/etc/passwd has _rtkit with a leading underscore)

**Comment by espectalll** [comment]
This sounds to me like an elogind issue, but I don't know how to properly debug it yet :thinking:

**Comment by espectalll** [comment]
OK, it's a ConsoleKit2-related issue. Uninstalling it actually fixes it all - no idea why tho.

**Comment by Oreo639** [comment]
Yep, thanks. That fixes the user profiles issue and the gdm issue.

**Comment by maxice8** [comment]
Status on this ?

**Comment by espectalll** [comment]
Just verified using a clean VM where I installed `gnome`, `gnome-apps` and `ConsoleKit2` – the issue is still there.

**Comment by Oreo639** [comment]
Still an issue btw.

**Comment by b4dtR1p** [comment]
no news?

**Comment by espectalll** [comment]
It seems fixed here! Can other people check?

**Comment by Oreo639** [comment]
Not fixed for me. Tried reinstalling using the cinnamon image (which includes consolekit2) and gdm gnome still does not display the users properly.

**Comment by Oreo639** [comment]
The issue seems fixed now.

**Comment by Cogitri** [comment]
Yup, now that Void has switched to using elogind at more places this should work.

**Comment by protonesso** [comment]
@axaxs I made a patch for accountsservice to work with consolekit. GNOME shows users now: https://github.com/ataraxialinux/ataraxia/blob/master/stuff/accountsservice/0001-revert-lib-don-t-set-loaded-state-until-seat-is-fetc.patch

**Comment by xtraeme** [comment]
consolekit2 is unsupported in void, use elogind.
