### ISSUE TITLE
[Package Request] Hyprland

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#37544]
[Hyprland](https://github.com/vaxerski/Hyprland) is a dynamic tiling Wayland compositor based on wlroots that doesn't sacrifice on its looks.

**Comment by mrkcee** [comment]
I was able to build a package (version 0.6.2beta) for this and currently using it. You will need the following:
- wlroots package based on commit 5c4384a1330faedf975c8b8644881d50390f3613
- Hyprland source where the subproject reference to wlroots build is removed and replaced it as dependency since Void already has a separate wlroots package (Hyprland includes wlroots in their build). You can do this by patching.

With these said, I think we may have to wait until wlroots releases a new version before we can include it in the repository.

**Comment by JamiKettunen** [comment]
Upstream doesn't seem very interested to be buildable against tagged wlroots versions, see https://github.com/hyprwm/Hyprland/issues/302

**Comment by JuniorSuperTux** [comment]
But what if we create a seperate package especially for Hyprland (wlroots-hyprland)?

**Comment by paper42** [comment]
> But what if we create a seperate package especially for Hyprland (wlroots-hyprland)?

That won't be accepted, we don't want to take care of a development wlroots version. Stable releases are expected to use stable releases of external system dependencies, if they don't want to do that, we won't probably package them.

**Comment by JuniorSuperTux** [comment]
I think as of right now this issue of wlroots has been resolved? But hyprland's makefile still builds it, so some patches would need to be applied

**Comment by Duncaen** [comment]
https://github.com/hyprwm/Hyprland/pull/552, still the same situation.

**Comment by TheHolyTachanka** [comment]
Any updates?

**Comment by JamiKettunen** [comment]
@TheHolyTachanka [Nope](https://github.com/hyprwm/Hyprland/issues/1709), I doubt anything will change in a very long time (possibly never). Feel free to create a local package (or otherwise install manually) but it won't be in the repo until the situation changes.
