### ISSUE TITLE
salt broken after Python 3.12 update

### ISSUE THREAD

**Issue by tsndqst** [void-linux/void-packages#46626]
### Is this a new report?

Yes

### System Info

Void 6.1.55_2 x86_64 AuthenticAMD uptodate FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

salt-3005_3

### Expected behaviour

Running `salt` should print usage information for the `salt` command.

### Actual behaviour

salt fails to load.

```
$ salt
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/salt", line 33, in <module>
    sys.exit(load_entry_point('salt==3005', 'console_scripts', 'salt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/salt", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 861, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for salt
```

### Steps to reproduce

run `salt`

**Comment by tsndqst** [comment]
This may be due to distutils.  It isn't removed until 3006.  https://github.com/saltstack/salt/pull/63309

**Comment by classabbyamp** [comment]
try installing python3-setuptools

**Comment by tsndqst** [comment]
it's already installed.

**Comment by classabbyamp** [comment]
is this fixed by https://github.com/void-linux/void-packages/compare/22c4f0d5...5f5d9677 ?

**Comment by tsndqst** [comment]
> is this fixed by [22c4f0d...5f5d967](https://github.com/void-linux/void-packages/compare/22c4f0d5...5f5d9677) ?

That definitely got it closer @classabbyamp.  With that update and some dependency changes I was able to get salt-master and salt-minion running.  I am still experiencing communication issues

The dependency changes I made are in this PR:  https://github.com/void-linux/void-packages/pull/46788
