### ISSUE TITLE
Some packages that have kernel.d are always trying to modify vmlinuz-${version} even if dracut-uefi is used.

### ISSUE THREAD

**Issue by piekay** [void-linux/void-packages#53299]
### Is this a new report?

Yes

### System Info

Void 6.6.63_1 x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

efibootmgr-18_1, sbsigntool-0.9.4_6

### Expected behaviour

The packages should include a configurable hook in /etc/default, that allows a user to set the file path of the /etc/kernel.d script, so that UKIs or non standard vmlinuz paths can be affected by these hooks. The file /efi/EFI/BOOT/void/Linux-${VERSION} should be just as affected as the default /boot/vmlinuz-${VERSION}

### Actual behaviour

Due to the hardcoded nature of the file paths, only /vmlinuz-${VERSION} is affected by these scripts.

### Steps to reproduce

1. Install dracut-uefi and the affected packages (efibootmgr-18_1, sbsigntool-0.9.4_6)
2. configure the packages using /etc/default to your liking
3. run dpkg-reconfigure -fa
4. Notice that the UKI neither gets registered by efibootmgr, nor gets signed by sbsigntool

**Comment by piekay** [comment]
I'm currently working on updating the scripts. Only sbsigntool and efibootmgr are tested, other packages with a hook in /etc/kernel.d might be affected too.

**Comment by classabbyamp** [comment]
why are you using dpkg on void?

**Comment by piekay** [comment]
> why are you using dpkg on void?

Thanks for the hint. I just messed up the command. It's fixed now

**Comment by piekay** [comment]
Should get resolved with #53301 and #53303

**Comment by dkwo** [comment]
I think this issue is still present, as e.g. `efibootmgr` does nothing to uki, and one has to use a custom hook.

**Comment by piekay** [comment]
It is, that's why the issue is still open. The current efibootmgr solution isn't optimal in general

**Comment by piekay** [comment]
Just to recap the current situation. You can set dracut-uefi as default with xbps-alternatives -s dracut-uefi thus no custom config is needed for only it to run. One still needs custom scripts for full UKI support. 

I currently put 
`preserve=/etc/kernel.d/post-install/40-sbsigntool
preserve=/etc/kernel.d/post-install/50-efibootmgr
`
into my /etc/xbps.d custom config and replace these scripts with custom versions. This isn't a great solution though. The efibootmgr script probably should be reworked in general and sbsigntool is outdated in void-packages anyway. I am currently trying to get sbsigntool to version 1.9.5, but I am not experienced enough with xbps-src and sbsigntool to guarantee any of it. If anyone is interested in getting native singed UKI support to void any help is appreciated

**Comment by dkwo** [comment]
I am in a similar situation, but I use `sbctl` (which is currently up to date), and custom efibootmgr and scbtl hooks.
I think at least the efibootmgr hook could be expanded to deal with uki.
