### ISSUE TITLE
wine stopped working after update to 10.9

### ISSUE THREAD

**Issue by xeroxslayer** [void-linux/void-packages#55697]
### Is this a new report?

Yes

### System Info

Void 6.12.32_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFF

### Package(s) Affected

wine-10.9_1

### Expected behaviour

To work.

### Actual behaviour

It just fails to work at all. I've attached logs (they're too big to be pasted here) with the following commands that correspond to the names of the logs.

```
winecfg-original-wine-dir.log --> WINEDEBUG=+seh,+loaddll,+module,+tid,+relay winecfg
winecfg-empty-wine-dir.log --> WINEDEBUG=+seh,+loaddll,+module,+tid,+relay winecfg
wine-winamp.log --> WINEDEBUG=+seh,+loaddll,+module,+tid,+relay wine $HOME/.wine/dosdevices/c:/Program\ Files\ \(x86\)/Winamp/winamp.exe
```

### Steps to reproduce

I don't think reproducing steps will actually make this reproducable, but here goes.

1. Install wine.
2. Try and run anything with it, or just run `winecfg`.

[wine-logs.zip](https://github.com/user-attachments/files/20669516/wine-logs.zip)

**Comment by chrysos349** [comment]
> Try and run anything with it

launching winamp-2.95 under the current wine works for me.

**Comment by xeroxslayer** [comment]
That was just a test, as in what happens when you load an application through it, just to generate the log. It doesn't work at all.

I tried scrubbing the volume for errors, none whatsoever. Force redownload and reinstall all wine packages, no dice.

It worked fine with wine ~~10.8~~ ~~10.4~~ 10.5 (sorry, my bad) (again, my bad). I have snapshots, so went back and just set the packages to hold, but that's not really a solution, is it.

I do have to note that this rig is fairly old, a Core2 Quad, 4GB RAM with an integrated GPU, Intel G43, OpenGL 1.4, but I know wine doesn't have a version limitation. Still, to eliminate this as a possible problem, I tried running any app just with `LIBGL_ALWAYS_SOFTWARE=1`, (and I confirmed it's working, `LIBGL_ALWAYS_SOFTWARE=1 glxinfo | grep -i "opengl renderer"` returns `llvmpipe`), nope, same thing.
 
Basically, this is the issue.

```
0024:warn:module:map_wow64cpu failed to open wow64cpu, status 0xc0000034
0024:trace:module:build_module loaded L"\\??\\C:\\windows\\syswow64\\start.exe" 00351978 00400000
0024:trace:loaddll:build_module Loaded L"C:\\windows\\syswow64\\start.exe" at 00400000: builtin
0024:trace:module:load_dll looking for L"kernel32.dll" in (null)
0024:warn:module:load_dll Failed to load module L"kernel32.dll"; status=c0000135
wine: could not load kernel32.dll, status c0000135
```

But the bins are there, I've checked.

**Comment by zlice** [comment]
i see wow64 there? you don't have wine-32bit installed?

i have a similar issue with wow64 but it started further back https://github.com/void-linux/void-packages/issues/55110 i suspect glibc update is related but not sure

**Comment by xeroxslayer** [comment]
Yes, I do have wine-32bit installed. Here are all of the wine packages I have installed.

```
wine-10.9_1
wine-32bit-10.9_1
wine-common-10.9_1
wine-mono-10.0.0_1
wine-tools-10.9_1
```

It's just that the index is 64-bit, that's all.

I can't recall if I updated to the latest version the last few months, that rig had to work 24/7 trying to recover files from a dying drive, so it basically worked for about a month and a half non-stop, so I avoided to update it. I also had snapshots disabled during this time, so the last snapshot I had was with wine 10.4, and 10.4 worked just fine.

**Comment by Piraty** [comment]
I installed a big piece of windows sotware last week using `wine-10.7_1` , works fine.

**Comment by fvalasiad** [comment]
When I updated the package to 10.9, I tried both launching a mixed WoW64 win64/win32 install AND running a 32bit binary using the experimental new WoW64 mode.

Everything worked fine, and since I don't see as many users reporting this compared to last time we accidentally broke wine, I'll assume something is wrong with your install instead.

Please run the command with strace until the error pops up and post the log in a pastebin and then here. I can help you debug it this way.

`strace -f <your command> 2>log.txt`

**Comment by xeroxslayer** [comment]
There is no "till the error pops up", it just doesn't work, at all, it can't load anything.

Here is the log from `strace -f wine ~/.wine/dosdevices/c:/Program\ Files\ \(x86\)/Winamp/winamp.exe 2>winamp.log`.

[winamp.zip](https://github.com/user-attachments/files/20831587/winamp.zip)

**Comment by fvalasiad** [comment]
I can't see anything wrong in the strace log, and it in fact finds kernel32.dll.

Is winamp the only one that doesn't work? Have you tried another program? Maybe it's wine that broke and not a packaging issue.

**Comment by xeroxslayer** [comment]
`winecfg` doesn't work as well. I've tried redownloading and reinstalling all of the wine related packages, new index, no errors when scrubbing the volume... everything worked fine with 10.4.

I don't have anything else installed, I'll try and just run a simple binary, though I doubt that will work as well.

**Comment by fvalasiad** [comment]
huh?

`winecfg` should be working.

Try nuking your config, `rm -rf ~/.wine"

and run again.

**Comment by xeroxslayer** [comment]
I've renamed it (that counts as nuking) and I've tried running `winecfg` to recreate the index, it still fails.

```
wine: created the configuration directory '/home/user/.wine'
002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc0d463
wine: could not load kernel32.dll, status c0000135
```

Regarding running a simple Windows binary in the old wine index.

`wine ~/Desktop/Winamp\ 5.24\ \(Keygen\).exe`

```
002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0024:err:vulkan:vulkan_init_once Failed to load libvulkan.so.1
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```

OK, I install `vulkan-loader` and `vulkan-loader-32bit` (the former was already installed, the latter was missing), here is what I get.

```
002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```

**Comment by xeroxslayer** [comment]
OK, I tried loading CPU-Z (32-bit) in the old index, here is what happens.

```
002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: Unhandled exception 0x40000015 in thread 24 at address 005573D5 (thread 0024), starting debugger...
0044:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
```

OK, let's try the 64-bit version.

```
002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0044:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: Unhandled exception 0x40000015 in thread 3c at address 000000014014084A (thread 003c), starting debugger...
004c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
```

Same thing...

This might be a GPU issue from what I can see... I'm using a G43 IGPU with mesa drivers, nothing fancy, just something to give a video output.

**Comment by zlice** [comment]
old igpu, have you tried libva downgrade? https://github.com/void-linux/void-packages/issues/53443

**Comment by xeroxslayer** [comment]
OK, so basically, I gotta rebuild libva 1.21.0, then downgrade with that package and... then what... hold that package? I mean... that's not really a solution...

I will try it of course and report back.

**Comment by zlice** [comment]
ya if it works may just have to make some noise in the libva 830 issue in that above issue. not sure if it was a "were quitting supporting old stuff" thing or theyre going to fix it in a newer release eventually.

**Comment by xeroxslayer** [comment]
OK, I tried downgrading, that didn't help at all, `vainfo` reported the same error message as VA-API 1.22.0.

```
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Wine still fails to load anything.

```
wine ~/Desktop/CPU-Z.exe

002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0044:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: Unhandled exception 0x40000015 in thread 3c at address 000000014014084A (thread 003c), starting debugger...
004c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
```

Here is what `vainfo` reports with the latest libva.

```
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Maybe it's not related to the GPU, maybe they're two different problems... as I said, this started happening with a wine update, not a libva update.

**Comment by xeroxslayer** [comment]
OK, I seem to have been missing `libva-intel-driver` (never needed it before though), and now `vainfo` reports the driver used properly.

```
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.21 (libva 2.21.0)
vainfo: Driver version: Intel i965 driver for Intel(R) G41 - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
```

But I still can't run anything in wine...

```
wine ~/Desktop/CPU-Z.exe

002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0044:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: Unhandled exception 0x40000015 in thread 3c at address 000000014014084A (thread 003c), starting debugger...
004c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
```

Then I tried upgrading to the latest version of libva and tried running something in wine again, still no dice.

```
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Intel i965 driver for Intel(R) G41 - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
```

```
wine ~/Desktop/CPU-Z.exe

002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0034:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
0044:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
wine: Unhandled exception 0x40000015 in thread 3c at address 000000014014084A (thread 003c), starting debugger...
004c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc4c173
```

**Comment by zlice** [comment]
> wine: created the configuration directory '/home/user/.wine'
> 002c:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x6fffffc0d463
> wine: could not load kernel32.dll, status c0000135

c0000005 is STATUS_ACCESS_VIOLATION

c0000135 is ERROR_MOD_NOT_FOUND

and the other below those

0x40000015 is STATUS_FATAL_APP_EXIT

this `nodrv` sounds like it doesn't detect if youre using wayland or x11. quick look at the code looks like it tries to detect that in `load_display_driver() > load_desktop_driver()` which has the "the explorer process failed to start" bit

```
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```

i assume permissions on /home/ dir are right or way more things than wine would be fubar?

what wayland/x11 setup are you using? doubt different display server / window manager would help or tell much but if it worked that'd tell something ig.

if going back to 10.4 still works, it for sure has to be a wine bug. i imagine building and bisecting commits on a core 2 quad will be a pain. but you would probably have to build and track down yourself since very few people are still on that old of hardware.

**Comment by zlice** [comment]
0927c5c3da7cda8cf476416260286bd299ad6319

10.4-^
10.5-v

f3843ea16b85012d0d0ca0f4f95a4c87c97d03f9

**Comment by xeroxslayer** [comment]
> i assume permissions on /home/ dir are right or way more things than wine would be fubar?

Yeah, I mean... everything else works fine. No problems shifting things from one dir to another, as a regular user of course. Haven't checked permissions on every single file, but if things were not as they should, as you said, I would expect a lot more to be not working properly.

> what wayland/x11 setup are you using? doubt different display server / window manager would help or tell much but if it worked that'd tell something ig.

Just plain old Void with xfce out of the box, X11 by default.

> if going back to 10.4 still works, it for sure has to be a wine bug. i imagine building and bisecting commits on a core 2 quad will be a pain. but you would probably have to build and track down yourself since very few people are still on that old of hardware.

I have newer hardware, a 3rd gen i7 and a 1st gen i7, this is just something I have working in the workshop, just to have something handy when I need a PC.

So, your suggestion is to try and build wine 10.5 and related packages, then try and force install that to try and find out exactly which wine version broke things? OK, I can try that. Might take a few days, but I'll try. Might be 10.5, might be 10.9, we'll see 😂.

And here is proof that wine did work, except I have no idea how I got the version wrong (again), it's version 10.5, not 10.4 😂. Sorry, I was probably shifting between snapshots and one of them had wine 10.4, so that kinda got stuck in my memory.

![Image](https://github.com/user-attachments/assets/bb98e13e-1306-4683-95de-a6b1da6d2227)

**Comment by fvalasiad** [comment]
I can compile a wine 10.4 version xbps if you want to, It'll take 15-20 minutes since it's gonna be inside a VM but better than the days you are describing quite honestly :).

But seriously, set up timeshift.

**Comment by xeroxslayer** [comment]
Actually, I have version 10.5 (as I said, sorry again 😂), so 10.6 at least.

And I have Timeshift set up 😂, I was just trying to figure out when things broke, so I might have loaded a snapshot a week or a few days before the last one taken that had wine working. As I said, I did a pause in taking snapshots, this rig was doing ddrescue on a drive for a month and half and then I never checked if wine worked, for a few days at least, and that's when new snapshots got created, and... oh well 😂.

So, I presume I can safely update and just hold these?

```
wine-10.5_1
wine-32bit-10.5_1
wine-common-10.5_1
wine-mono-10.0.0_1
wine-tools-10.5_1
```

**Comment by zlice** [comment]
fv: what's timeshift? (ah ok looked it up, neat)

xero: to bisect the commits i would not use xbps, ive done it before and since it's not incremental it hurts. if you can, i'd build it on your i7 and tar+copy it to the machine somehow then do `sudo make install`, would have to be faster than the core2quad.

`git clone https://github.com/wine-mirror/wine` and do a `git bisect good f3843ea16b85012d0d0ca0f4f95a4c87c97d03f9` (10.5) then `git bsiect bad 040e1333b1f4cf73d6877daec15495a8be42324a` (10.6)

^^^ if you think or are not sure that it broke in 10.6 just do 10.7 or find another `Release; 10.x` in `git log`

build

`./configure --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu '--libdir=${exec_prefix}/lib64' --with-xshm --enable-win64 --libdir=/usr/lib --enable-archs=i386,x86_64 && make -j18 && sudo make install` (change -j18 appropriate for your cpus core count)

then `git bisect <good/bad>` between make and make install. takes forever but

or ya you can just hold on 10.5, no telling if wine will start working again in the future w/o a bug report though

**Comment by xeroxslayer** [comment]
> fv: what's timeshift?

A GUI for taking and managing snapshots, it's got a scheduler, hourly, daily, weekly, monthly, at boot, etc. Mainly used for BTRFS, but you can use it with EXT* and rsync as well.

It's pretty cool, try it :).

> or ya you can just hold on 10.5, no telling if wine will start working again in the future w/o a bug report though

I know, that was my next plan, but then again, they might do something else and break things even further, my hardware is not exactly new, I don't want to be left hanging regarding this. I'm well aware that things will eventually shift in that direction, but I thought I had at least another 5 years for basic things on this thing and my other hardware 😂.

Things already broke for an old P4 I had, which didn't bother me that much, it barely ran Wine, it was more of a test if it CAN run Wine, so not really bummed about that.

**Comment by xeroxslayer** [comment]
OK, just to confirm, I've updated Void on that rig, just held back the wine packages, yes, wine 10.5 still works with Void up to date.

**Comment by fvalasiad** [comment]
Timeshift also has a CLI btw.

**Comment by zlice** [comment]
i just wanted to put these somewhere for whoever happens to come across. maybe they'd help with your specific issue, would be good to know if they did. matches title of 'wine stopped working' but way earlier than 10.9

#### fallout 3/nv mwmhints keeps minimizing window - 10.4

changes in x11drv cause some fullscreen games to constantly minimize.

this patch is not a real fix, as it makes games stay up in the background for me, and does not work on openbox/jwm at all.

https://bugs.winehq.org/show_bug.cgi?id=58443

[fo3-minwinfail-mwmhints-chaos.patch.txt](https://github.com/user-attachments/files/21196407/fo3-minwinfail-mwmhints-chaos.patch.txt)

#### buggy mwmhints can't keep fullscreen straight - 10.8

changes in x11drv cause mwmhints to constantly try to toggle fullscreen windows in some games. alt+tab especially makes this apparent, for instance watch_dogs in openbox will need 3 alt+tabs with 2 windows and toggle decore. in fluxbox the focus acts normal but decor toggles so you get a cut-off fullscreen with no borders.

https://bugs.winehq.org/show_bug.cgi?id=58442

[wd1-2-fix-fullscreen-toggle.patch.txt](https://github.com/user-attachments/files/21196437/wd1-2-fix-fullscreen-toggle.patch.txt)

#### watch_dogs splash screen broken in some wm - 10.3

flubox and i believe jwm can not get past splash screen. QS_SENDMESSAGE was added to the x11drv event loop and idk what that windows message translates to in x11.

https://bugs.winehq.org/show_bug.cgi?id=57954

[wd1-1-fix-splash-qspostmsg.patch.txt](https://github.com/user-attachments/files/21196454/wd1-1-fix-splash-qspostmsg.patch.txt)

#### spec ops window disappears (bad mutter hack/fix) - 10.2

mutter and some other window managers do not 'withdraw unmapped' windows (x11 terms) when minimized. there was a hack to do this manually with wine but it broke some window managers.

fluxbox fix has a pr pending and honestly don't know when/if that will ever be merged. other window managers may be affected (especially minimalist ones)

https://bugs.winehq.org/show_bug.cgi?id=58223

[specops-mutterhackundo.patch.txt](https://github.com/user-attachments/files/21196548/specops-mutterhackundo.patch.txt)

#### wow64 attr sizeof ptr - gcc 14.2.1?

previously mentioned bug, wow64 some 32bit functionality is borken due to i assume gcc mismatching pointer sizes

https://bugs.winehq.org/show_bug.cgi?id=58469

[wow64attr-ptrsz-gcc.patch.txt](https://github.com/user-attachments/files/21196502/wow64attr-ptrsz-gcc.patch.txt)

**Comment by xeroxslayer** [comment]
> matches title of 'wine stopped working' but way earlier than 10.9

Yes, actually, way earlier than 10.9 on my old P4 rig. I also have a dual Xeon on a HP XW8000 workstation, wine on that one kept on chugging after wine broke on the P4. I haven't checked if that still works, that rig is on the side and I haven't powered it on in a long time, at least a few months, but if you think it might help, I will power it on and see if latest wine version works on that dual Xeon rig. Xeon's are from the P4 era, so basically, a P4 with HT and MMX2, that's about it.

I can't confirm anything regarding games to be honest, I don't game. And while I know that the target audience of wine are gamers, it's not bad if they look at us regular users from time to time and try not to break things for us 😅.

I was just about to get git hashes for wine 10.6 and onwards so that I can build and install wine 10.6, so I can pinpoint at exactly which version wine broke. Will get back with results.

**Comment by xeroxslayer** [comment]
How do you build the 32-bit multilib packages anyway 🤔?

EDIT: Never mind, found it, it's a subpackage 🤦‍♂️.

**Comment by zlice** [comment]
`./xbps-src pkg wine && ./xbps-src pkg -m 32-masterdir wine` to build a 64 and 32bit version, then the xbps files are in `hostdir/binpkgs/multilib`

**Comment by classabbyamp** [comment]
> `./xbps-src pkg wine && ./xbps-src pkg -m 32-masterdir wine` 

use `-A i686` not `-m 32-masterdir`

**Comment by xeroxslayer** [comment]
OK, wine 10.6 works fine, moving on to wine 10.7.

**Comment by xeroxslayer** [comment]
10.7 works fine as well, moving on to 10.8.

**Comment by xeroxslayer** [comment]
10.8 works as well, moving to 10.9

**Comment by xeroxslayer** [comment]
Hm, strange...

```
fatal: unable to read tree (4a28bd980ced96b40c83f5e6c34ade80d9e399dd)
```

This is for the commit in which the template for wine was updated from 10.8 to 10.9.

It was just 3 lines, the version and the hashes, so I did the changes manually.

Oh, this one has a rev_2, maybe that's why it didn't work. Checking out the hash of rev_2 is working fine.

OK, confirmed, wine 10.9 is the culprit, and I presume it had something to do with the removal of `libOSMesa` from the depends. Will try adding that back and report back.

**Comment by classabbyamp** [comment]
libOSMesa no longer exists

**Comment by xeroxslayer** [comment]
Well, I tried adding that, it's building as I'm writing now, we'll see what happens 🤷‍♂️...

It did find it in repo though, so...

**Comment by classabbyamp** [comment]
libOSMesa was a deprecated component of mesa that they removed in 25.1. even if it "exists", it's the wrong version

**Comment by xeroxslayer** [comment]
the 32bit depend just said `libOSMesa-32bit>=0`, so... IDK 🤷‍♂️...

**Comment by xeroxslayer** [comment]
OK, that wasn't the issue, which means that it's probably an upstream issue, something between 10.8 and 10.9 broke things on older rigs.

So, do I open up an issue [here](https://bugs.winehq.org/), or...

**Comment by xeroxslayer** [comment]
OK, here is the issue for reference.

https://bugs.winehq.org/show_bug.cgi?id=58513

**Comment by xeroxslayer** [comment]
Confirmed, this commit is causing the problem.

https://gitlab.winehq.org/wine/wine/-/commit/745a11a231816a7d82490156c72a18c39216a14c

**Comment by fvalasiad** [comment]
Good job, I guess it's best you stick to 10.8 until they resolve it upstream, unless we wanna try reverting it and dealing with any arising issues.

**Comment by zlice** [comment]
10.8 lol im on 10.1

**Comment by Piraty** [comment]
@Hoshpak

**Comment by xeroxslayer** [comment]
Issue fixed, wine works again on LGA775 and 771.
