### ISSUE TITLE
qgis: No module named 'PyQt6.QtGui'

### ISSUE THREAD

**Issue by nezos** [void-linux/void-packages#57758]
### Is this a new report?

Yes

### System Info

Void 6.12.55_1 x86_64 GenuineIntel uptodate rrrmF

### Package(s) Affected

qgis-3.44.4_1

### Expected behaviour

qgis should open without error

### Actual behaviour

qgis disables python support after showing the following error:

```
Couldn't load PyQt.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/PyQt/QtGui.py", line 26, in 
    from PyQt6.QtGui import *
ModuleNotFoundError: No module named 'PyQt6.QtGui'


Python version:
3.13.9 (main, Oct 19 2025, 20:47:14) [GCC 14.2.1 20250405]

QGIS version:
3.44.4-Solothurn 'Solothurn', exported

Python path:
['/usr/share/qgis/python', '/home/myuser/.local/share/QGIS/QGIS3/profiles/default/python', '/home/myuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python313.zip', '/usr/lib/python3.13', '/usr/lib/python3.13/lib-dynload', '/home/myuser/.local/lib/python3.13/site-packages', '/usr/lib/python3.13/site-packages']
```

### Steps to reproduce

run qgis

### Notes

previous qt5 packages had capital letters in P and Q:  python3-PyQt5

**Comment by sgn** [comment]
Fixed

**Comment by nezos** [comment]
The problem still exists after installing qgis-3.44.4_1:

`Couldn't load PyQGIS.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/core/__init__.py", line 28, in 
    from qgis._core import *
ModuleNotFoundError: No module named 'PyQt6.QtWidgets'


Python version:
3.13.9 (main, Oct 19 2025, 20:47:14) [GCC 14.2.1 20250405]`

I tried removing everything and reinstalling but it did not work.

**Comment by sgn** [comment]
Update `qgis` to `3.44.4_2` plz

**Comment by amok-dma** [comment]
After updating QGIS to version 3.44.4_2 it shows 2 warnings:

1)

```
Couldn't load PyQGIS.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/core/__init__.py", line 28, in 
    from qgis._core import *
ModuleNotFoundError: No module named 'PyQt6.QtWidgets'


Python version:
3.13.9 (main, Oct 19 2025, 20:47:14) [GCC 14.2.1 20250405]

QGIS version:
3.44.4-Solothurn 'Solothurn', exported

Python path:
['/usr/share/qgis/python', '/home/amok/.local/share/QGIS/QGIS3/profiles/default/python', '/home/amok/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python313.zip', '/usr/lib/python3.13', '/usr/lib/python3.13/lib-dynload', '/usr/lib/python3.13/site-packages']
```

2)

```
An error occurred during execution of following code:
from qgis.core import QgsApplication as _QgsApplication

def _qgis_app_init_qgis():
  raise RuntimeError('QgsApplication.initQgis() must never be called from within the QGIS application. This method is exclusively for standalone scripts.')

_QgsApplication.initQgis = _qgis_app_init_qgis

def _qgis_app_exit_qgis():
  raise RuntimeError('QgsApplication.exitQgis() must never be called from within the QGIS application. This method is exclusively for standalone scripts.')

_QgsApplication.exitQgis = _qgis_app_exit_qgis



SystemError: globals must be a real dict


Python version:


QGIS version:
3.44.4-Solothurn 'Solothurn', exported

Python path:
```



And after installing python3-pyqt6-widgets QGIS shows another 1 new and 1 repeated warning:

1)

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/__init__.py", line 85, in 
    import qgis.gui
  File "/usr/share/qgis/python/qgis/gui/__init__.py", line 691, in 
    QgsCodeEditor.Mode.ScriptEditor.__doc__ = "Standard mode, allows for display and edit of entire scripts"
    ^^^^^^^^^^^^^
NameError: name 'QgsCodeEditor' is not defined


Python version:
3.13.9 (main, Oct 19 2025, 20:47:14) [GCC 14.2.1 20250405]

QGIS version:
3.44.4-Solothurn 'Solothurn', exported

Python path:
['/usr/share/qgis/python', '/home/amok/.local/share/QGIS/QGIS3/profiles/default/python', '/home/amok/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python313.zip', '/usr/lib/python3.13', '/usr/lib/python3.13/lib-dynload', '/usr/lib/python3.13/site-packages']
```

2)

```
An error occurred during execution of following code:
from qgis.core import QgsApplication as _QgsApplication

def _qgis_app_init_qgis():
  raise RuntimeError('QgsApplication.initQgis() must never be called from within the QGIS application. This method is exclusively for standalone scripts.')

_QgsApplication.initQgis = _qgis_app_init_qgis

def _qgis_app_exit_qgis():
  raise RuntimeError('QgsApplication.exitQgis() must never be called from within the QGIS application. This method is exclusively for standalone scripts.')

_QgsApplication.exitQgis = _qgis_app_exit_qgis



SystemError: globals must be a real dict


Python version:


QGIS version:
3.44.4-Solothurn 'Solothurn', exported

Python path:
```

**Comment by nezos** [comment]
sorry I also meant 3.44.4_2, it was a typo

**Comment by sgn** [comment]
Try install `python3-pyqt6-widgets`

**Comment by nezos** [comment]
Installing python3-pyqt6-widgets helped but didn't solve the problem.

I then installed: python3-pyqt6-position to remove the error for PyQt6.Positioning (came up next).

Then, I didn't manage to  pass the following error:
`Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/__init__.py", line 85, in 
    import qgis.gui
  File "/usr/share/qgis/python/qgis/gui/__init__.py", line 691, in 
    QgsCodeEditor.Mode.ScriptEditor.__doc__ = "Standard mode, allows for display and edit of entire scripts"
    ^^^^^^^^^^^^^
NameError: name 'QgsCodeEditor' is not defined`

I have already installed: python3-pyqt6-sip, tried installing additionally sip but didn't help

**Comment by nezos** [comment]
**!SOLUTION!**
I checked your build log in build.voidlinux.org and I noticed:

```
-- Found PyQt6 version: 6.10.0

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from PyQt6.Qsci import QSCINTILLA_VERSION_STR; print(QSCINTILLA_VERSION_STR)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PyQt6.QtWidgets'
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
```

I changed the template to include in _pyqt="....  python3-pyqt6-widgets" and buildt locally:

```
-- Found sip-build executable: /usr/bin/sip-build
-- Found PyQt6 version: 6.10.0

-- Found QScintilla2 PyQt module: 2.14.1

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
```

Now the next error that appeared is:
`ModuleNotFoundError: No module named 'PyQt6.uic'`

so I installed python3-pyqt6-devel-tools and it worked!

**Comment by ar-jan** [comment]
Thanks for looking into this! I'd noticed the problem but didn't have time to look at it.
