### ISSUE TITLE
Qt 6.10: Cannot link Qt6::GuiPrivate in Cmake

### ISSUE THREAD

**Issue by METhOphetamine** [void-linux/void-packages#57777]
### Is this a new report?

Yes

### System Info

Every ARCH in the CI had this issue but I locally ran it at `Void 6.12.54_1 x86_64-musl GenuineIntel notuptodate rrn`

### Package(s) Affected

QXlsx (my not yet merged PR) and one of these 2: qt6-base-devel-6.10.0_3 qt6-base-private-devel-6.10.0_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Could not find upstream issue but found (probably) the same one in Nix Packages: https://github.com/NixOS/nixpkgs/issues/454777

### Expected behaviour

Linking Qt6::GuiPrivate should work according to this: https://doc.qt.io/qt-6/qtguiprivate-module.html

### Actual behaviour

See this failed build: https://github.com/void-linux/void-packages/actions/runs/18938962878/job/54299658609#step:7:69

### Steps to reproduce

See my template from the PR. But looking at the CMakeLists.txt it's just linking the library as described on the Qt website:

```
find_package(Qt6 REQUIRED COMPONENTS Gui)
target_link_libraries(mytarget PRIVATE Qt6::GuiPrivate)
```

**Comment by METhOphetamine** [comment]
Update: This is an upstream Qt bug and it's already fixed in their development branch. The Qt docs contain outdated build instructions. https://bugreports.qt.io/browse/QTBUG-141106

~~I'm probably gonna patch the CMakeLists.txt and/or report to QXlsx upstream~~
Edit: QXlsx upstream has already been fixed for some time now, they just have not released a new version containing the fix since then.

**Comment by MhmRhm** [comment]
Building [QXlsx](https://github.com/QtExcel/QXlsx) with 6.10.1 I am still seeing this issue:

```
CMake Error at /home/mohammad/Documents/Processing-build-linux-default-release/_deps/qxlsx-src/QXlsx/CMakeLists.txt:167 (target_link_libraries):
  Target "QXlsx" links to:

    Qt6::GuiPrivate

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by sgn** [comment]
@MhmRhm Read those above message again! Nothing to do with us.

**Comment by METhOphetamine** [comment]
You need to use the master branch. Not the release. I have a suspicion that I'm talking to someone's agentic bot though. Otherwise I have no idea why complain about it in the Void Linux package repo.

**Comment by MhmRhm** [comment]
My apologies you both are right. I was checking out the master branch in my build directory instead of declaring it in fetch content at configuration.

**Comment by LXGMAX** [comment]
I solved with `find_package(Qt6 REQUIRED COMPONENTS GuiPrivate)`

from: https://www.reddit.com/r/QtFramework/comments/1o42h63/qtguiprivate_target_not_found/
